---
# tasks file for nginx_proxy

- name: Установка Nginx
  apt:
    name: "nginx"
    state: present

- name: Замена конфиругационного файла nginx
  ansible.builtin.template:
    src: "nginx.conf.j2"
    dest: "/etc/nginx/nginx.conf"
  when: "'vm_2' in inventory_hostname"
  notify: "Nginx Reloader"

