---
# tasks file for default_packages

- name: Меняем имя машины
  shell: "echo {{ inventory_hostname }} > /etc/hostname"
  when: "inventory_hostname != ansible_hostname"

- name: Установка программ #Имя задачи 
  apt: #Используемый модуль
    name: "{{ item }}" #Имя пакета из цикла
    state: present #Параметр действия. present - установить, absent - удалить
  loop:
    - "{{ packages_to_install }}" #Цикл будет перебирать все значения из переменной "packages"
  when: ansible_distribution == "Ubuntu" # Выполнится только на Debian системах
