---
linux:  # Группа хостов
  children:  # Обозначение, что будет подгруппа хостов
    nginx:  # Имя подгруппы хостов
      hosts:  # Узлы группы
        vm_1:  # Имя машины
          ansible_host: 158.160.12.251
        vm_2:
          ansible_host: 158.160.5.200
            #your_variable: nginx_1
        vm_3:
          ansible_host: 89.169.182.80
          your_variable: nginx_3
  vars:  # Переменные, доступные или используемые для всех подгрупп
    ansible_user: "ubuntu"
      #    ansible_password: "qwerty"
    connection_protocol: ssh  # тип подключения
    ansible_become: true  # Становиться ли другим пользователем после подключения
